apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.helmServiceAccount }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.helmRole }}
  namespace: {{ .Values.rbac.tillerNamespace }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups: ["", "metrics.k8s.io", "extensions", "apps", "secrets", "serviceaccounts", "namespaces", "clusterroles"]
  resources: ["pods", "replicasets", "pods", "deployments", "services", "secrets", "serviceaccounts", "namespaces", "clusterroles"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "describe"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.tillerRoleBindingName }}
  namespace: {{ .Values.rbac.tillerNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.helmRole }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.helmServiceAccount }}
  namespace: {{ .Values.namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vnfmsimhelm.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "vnfmsimhelm.name" . }}
    chart: {{ template "vnfmsimhelm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http

  selector:
    app: {{ template "vnfmsimhelm.name" . }}
    release: {{ .Release.Name }}
