# Default values for vnfmsimhelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

env:
  vnfmendpoint: "http://192.168.56.126:32093"
  adaptorendpoint: "http://192.168.56.126:32080"


image:
  # uncomment and fill registry name
  registry: commscoperegistry:5000
  name: vnfmsimhelm
  tag: latest
  pullPolicy: IfNotPresent

service:
  #type: LoadBalancer
  #port: 4000
  type: NodePort
  port: 9093
  nodePort: 32093


namespace: default

# for the ingress functionallity - the ingress is the controller which exposes the newly deployed service
# Refer to the docs for more details
ingress:
  ingressNamespace: default
  minPort: 20000
  maxPort: 30000
  ingressLabel: ingress

# configuration for the rbac namespaces, service accounts, roles and binding names
rbac:
  helmServiceAccount: helm
  helmRole: tiller-user
  tillerServiceAccount: tiller
  tillerRoleBindingName: tiller-user-binding
  tillerNamespace: kube-system
